name: Build Datapack

on:
  push:
    branches: 'main'

jobs:
  build_pack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'
      - uses: actions/checkout@v4
        with:
          repository: slackow/packscript
          path: packscript
      - run: python packscript/packscript.py c -o AA_Endgame_Practice.zip
      - uses: actions/upload-artifact@v4
        with:
          name: AA_Endgame_Practice.zip
          path: AA_Endgame_Practice.zip
